---
Parameters: 
  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m1.small
    Description: Instance type that can be used
  SubnetParameter:
    Type: string
    Default: TestSubnet00
  KeyPairParameter:
    Type: string
    Default: keyPairTest00
    Description: Instance type that can be used
  

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ff8a91507f77f867
      InstanceType:
        Ref: InstanceTypeParameter
    Type: AWS::EC2::Subnet
    Properties: 
      Tags: 
      - Key: Name
        Name: !Ref SubnetParameter
